### ISSUE TITLE
KP/checkout/order: missing request parameter "ord_agb=1" in merchant confirmation url 

### ISSUE THREAD

**Issue by kaluzki** [topconcepts/OXID-Klarna-6#4]
https://github.com/topconcepts/OXID-Klarna-6/blob/85b222441cab887c59fd9146aa752ca193b51d1f/Core/KlarnaPayment.php#L161

Without this parameter customers have to confirm AGB twice in the last checkout "order" step.

this line solves this behaviour:
```php
...
"merchant_urls"     => array(
    "confirmation" => Registry::getConfig()->getSslShopUrl() . "?cl=order&oxdownloadableproductsagreement=1&ord_agb=1&fnc=execute&stoken=" . $sToken . $shopUrlParam,
),
...
```

**Comment by tc-hugo** [comment]
Issue fixed on version v4.0.0
Thank you for your feedback
